language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - yarn test --watchAll=false

deploy:
  provider: heroku
  api-key: $HEROKU_KEY
  app: $HEROKU_APP
  on: 
    branch: main